#!/bin/bash
# ============================================================
# Auto Script SSH By : ProgoCloud
# Module: core/system.sh - OS detection, package manager & system security
# ============================================================

get_ubuntu_codename() {
    local codename=""
    if [[ -r /etc/os-release ]]; then
        codename=$(awk -F= '$1 == "VERSION_CODENAME" {print $2}' /etc/os-release 2>/dev/null | tr -d '"'\''')
        [[ -z "$codename" ]] && codename=$(awk -F= '$1 == "UBUNTU_CODENAME" {print $2}' /etc/os-release 2>/dev/null | tr -d '"'\''')
    fi
    if [[ -z "$codename" ]] && command -v lsb_release >/dev/null 2>&1; then
        codename=$(lsb_release -cs 2>/dev/null || true)
    fi
    echo "${codename,,}"
}

is_known_eol_ubuntu_codename() {
    local codename="$1"
    case "$codename" in
        artful|bionic|cosmic|disco|eoan|groovy|hirsute|impish|kinetic|lunar|mantic|trusty|utopic|vivid|wily|xenial|yakkety|zesty)
            return 0
            ;;
        *)
            return 1
            ;;
    esac
}

rewrite_ubuntu_apt_sources() {
    local target_file="$1" codename="$2" mirror_host="$3"
    local has_security_pocket=1
    [[ "$mirror_host" == "old-releases.ubuntu.com" ]] && has_security_pocket=0

    {
        echo "# Auto-generated by ProgoCloud APT compatibility manager"
        echo "deb http://${mirror_host}/ubuntu/ ${codename} main restricted universe multiverse"
        echo "deb http://${mirror_host}/ubuntu/ ${codename}-updates main restricted universe multiverse"
        echo "deb http://${mirror_host}/ubuntu/ ${codename}-backports main restricted universe multiverse"
        if (( has_security_pocket == 1 )); then
            echo "deb http://${mirror_host}/ubuntu/ ${codename}-security main restricted universe multiverse"
        else
            echo "deb http://${mirror_host}/ubuntu/ ${codename}-security main restricted universe multiverse"
        fi
    } > "$target_file"
}

repair_ubuntu_apt_mirrors() {
    local codename
    codename=$(get_ubuntu_codename)
    [[ -z "$codename" ]] && return 1
    if is_known_eol_ubuntu_codename "$codename"; then
        switch_ubuntu_to_old_releases "$codename"
        return $?
    fi
    return 1
}

switch_ubuntu_to_old_releases() {
    local codename="$1"
    [[ -z "$codename" ]] && codename=$(get_ubuntu_codename)
    [[ -z "$codename" ]] && return 1
    if [[ -f /etc/apt/sources.list && ! -f /etc/apt/sources.list.pgy-backup ]]; then
        cp /etc/apt/sources.list /etc/apt/sources.list.pgy-backup 2>/dev/null || true
    fi
    rewrite_ubuntu_apt_sources /etc/apt/sources.list "$codename" "old-releases.ubuntu.com"
}

repair_debian_apt_mirrors() {
    local codename=""
    if [[ -r /etc/os-release ]]; then
        codename=$(awk -F= '$1 == "VERSION_CODENAME" {print $2}' /etc/os-release 2>/dev/null | tr -d '"'\''')
    fi
    [[ -z "$codename" ]] && return 1
    if [[ -f /etc/apt/sources.list && ! -f /etc/apt/sources.list.pgy-backup ]]; then
        cp /etc/apt/sources.list /etc/apt/sources.list.pgy-backup 2>/dev/null || true
    fi
    {
        echo "# Auto-generated by ProgoCloud APT compatibility manager"
        echo "deb http://deb.debian.org/debian ${codename} main contrib non-free"
        echo "deb http://deb.debian.org/debian ${codename}-updates main contrib non-free"
        echo "deb http://security.debian.org/debian-security ${codename}-security main contrib non-free"
    } > /etc/apt/sources.list
}

pgy_apt_update() {
    local apt_out
    export DEBIAN_FRONTEND=noninteractive
    if apt_out=$(apt-get update 2>&1); then
        return 0
    fi
    if [[ "$apt_out" =~ 404.*Not\ Found|archive\.ubuntu\.com|security\.ubuntu\.com ]]; then
        repair_ubuntu_apt_mirrors 2>/dev/null || repair_debian_apt_mirrors 2>/dev/null || true
        apt-get update -y 2>&1 || true
    fi
    return 0
}
tdz_apt_update() { pgy_apt_update "$@"; }

pgy_apt_install() {
    export DEBIAN_FRONTEND=noninteractive
    apt-get install -y --no-install-recommends "$@"
}
tdz_apt_install() { pgy_apt_install "$@"; }

pgy_apt_purge() {
    export DEBIAN_FRONTEND=noninteractive
    apt-get purge -y "$@"
}
tdz_apt_purge() { pgy_apt_purge "$@"; }

check_environment() {
    if [[ $EUID -ne 0 ]]; then
        echo -e "${C_RED}[ERROR] Script ini membutuhkan hak akses root.${C_RESET}"
        exit 1
    fi
}

ensure_pgytunnel_dirs() {
    mkdir -p "$DB_DIR" "$SSL_CERT_DIR" "$DNSTT_KEYS_DIR" "$BANDWIDTH_DIR" "$PGY_LIB_DIR" "$PGY_OPT_LIB_DIR"
    chmod 700 "$DB_DIR" "$SSL_CERT_DIR" "$DNSTT_KEYS_DIR" "$BANDWIDTH_DIR" 2>/dev/null || true
    chmod 755 "$PGY_LIB_DIR" "$PGY_OPT_LIB_DIR" 2>/dev/null || true
    [[ -f "$DB_FILE" ]] || touch "$DB_FILE"
    chmod 600 "$DB_FILE" 2>/dev/null || true
    [[ -f "$MANUAL_LOCK_FILE" ]] || touch "$MANUAL_LOCK_FILE"
    chmod 600 "$MANUAL_LOCK_FILE" 2>/dev/null || true
}
ensure_tdztunnel_dirs() { ensure_pgytunnel_dirs "$@"; }

ensure_pgytunnel_system_group() {
    if ! getent group pgyusers >/dev/null 2>&1; then
        groupadd -r pgyusers 2>/dev/null || groupadd pgyusers 2>/dev/null || true
    fi
    # Also ensure legacy group name for compatibility
    if ! getent group tdzusers >/dev/null 2>&1; then
        groupadd -r tdzusers 2>/dev/null || groupadd tdzusers 2>/dev/null || true
    fi
}
ensure_tdztunnel_system_group() { ensure_pgytunnel_system_group "$@"; }

harden_sshd_for_tunnel_stability() {
    local target="/etc/ssh/sshd_config.d/pgytunnel.conf"
    mkdir -p /etc/ssh/sshd_config.d
    cat <<'EOF' > "$target"
# Auto Script SSH By : ProgoCloud
# SSH Tunneling Optimization
ClientAliveInterval 30
ClientAliveCountMax 3
MaxSessions 100
MaxStartups 100:30:200
TCPKeepAlive yes
X11Forwarding yes
PermitTunnel yes
AllowTcpForwarding yes
GatewayPorts yes
Banner /etc/pgytunnel/bannerssh
EOF
    chmod 644 "$target" 2>/dev/null || true
}

_is_valid_ipv4() {
    local ip="$1"
    local rx='^([0-9]{1,3}\.){3}[0-9]{1,3}$'
    [[ "$ip" =~ $rx ]] || return 1
    local IFS='.'
    read -r -a octets <<< "$ip"
    for oct in "${octets[@]}"; do
        (( oct >= 0 && oct <= 255 )) || return 1
    done
    return 0
}

pgy_record_firewall_rule() {
    local tool="$1" proto="$2" port="$3"
    mkdir -p "$DB_DIR"
    echo "${tool}|${proto}|${port}" >> "$FIREWALL_STATE_FILE"
}
tdz_record_firewall_rule() { pgy_record_firewall_rule "$@"; }

pgy_remove_recorded_firewall_rules() {
    [[ -f "$FIREWALL_STATE_FILE" ]] || return 0
    while IFS='|' read -r tool proto port; do
        [[ -n "$tool" && -n "$proto" && -n "$port" ]] || continue
        case "$tool" in
            ufw)
                ufw delete allow "${port}/${proto}" >/dev/null 2>&1 || true
                ;;
            iptables)
                iptables -D INPUT -p "$proto" --dport "$port" -j ACCEPT 2>/dev/null || true
                ip6tables -D INPUT -p "$proto" --dport "$port" -j ACCEPT 2>/dev/null || true
                ;;
        esac
    done < "$FIREWALL_STATE_FILE"
    rm -f "$FIREWALL_STATE_FILE"
}
tdz_remove_recorded_firewall_rules() { pgy_remove_recorded_firewall_rules "$@"; }

check_and_open_firewall_port() {
    local port="$1" proto="${2:-tcp}"
    if command -v ufw >/dev/null 2>&1 && ufw status 2>/dev/null | grep -q "Status: active"; then
        ufw allow "${port}/${proto}" >/dev/null 2>&1 || true
        pgy_record_firewall_rule "ufw" "$proto" "$port"
    elif command -v iptables >/dev/null 2>&1; then
        iptables -C INPUT -p "$proto" --dport "$port" -j ACCEPT >/dev/null 2>&1 || {
            iptables -I INPUT -p "$proto" --dport "$port" -j ACCEPT >/dev/null 2>&1 || true
            pgy_record_firewall_rule "iptables" "$proto" "$port"
        }
    fi
}

check_and_open_firewall_port_range() {
    local start="$1" end="$2" proto="${3:-udp}"
    if command -v ufw >/dev/null 2>&1 && ufw status 2>/dev/null | grep -q "Status: active"; then
        ufw allow "${start}:${end}/${proto}" >/dev/null 2>&1 || true
    elif command -v iptables >/dev/null 2>&1; then
        iptables -C INPUT -p "$proto" --dport "${start}:${end}" -j ACCEPT >/dev/null 2>&1 || {
            iptables -I INPUT -p "$proto" --dport "${start}:${end}" -j ACCEPT >/dev/null 2>&1 || true
        }
    fi
}
